Require Go 1.20
elastic/apm-data pull request #113
Opened 2023-07-13 07:39 UTC by dmathieu

This upgrades to Go 1.20, so we can use slice-to-array conversion in #110.

2023-07-13 12:18 UTC, kruskall requested changes
This would require bumping APM Server go version too but we need to support the two latest go version.

2023-07-14 02:52 UTC, axw commented
@kruskall that's only relevant for libraries like apm-agent-go, not to apm-server.

2023-07-14 02:53 UTC, axw commented
(and we don't have any compatibility guarantees for _this_ library; it exists only to serve apm-server and friends)

2023-07-14 02:55 UTC, kruskall approved these changes

2023-07-14 02:56 UTC, kruskall commented
Ah sorry about that, I always mix the support policy :face_exhaling:

2023-07-17 07:59 UTC, merged